# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IdeA thinKING
email: iwongu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I de A thin KING
baseurl: ""
paginate: 5
url: "http://ideathinking.com"
twitter_username: iwongu
github_username: iwongu
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
